### ISSUE TITLE
input issue

### ISSUE THREAD

**Issue by LePlaYa** [hennneh/miniRT#53]
start with given scene, but recognize the error

A 1 128,128,128
C 0,10,0 0,-1,0 90
L -40,0,30 0.7
cy 0,0-1,0 0,0,1 3 6 255,0,255

vincenct say first object is the problem

**Comment by belgishboy** [comment]
when the first obj is failure, since count == 0, error doesnt get triggered

**Comment by belgishboy** [comment]
Fixed on Norm
